pipeline {
  agent {
    docker {
      image 'cypress/browsers:node12.16.2-chrome81-ff75'
    }

  }
  stages {
    stage('build') {
      steps {
        echo "Running build ${env.BUILD_ID} on ${env.JENKINS_URL}"
        sh 'pwd && ls -l '
        sh 'npm ci'
        sh 'pwd && ls -l ./node_modules'
        sh 'npm run cy:verify'
      }
    }

    stage('cypress parallel tests') {
      // https://jenkins.io/doc/book/pipeline/syntax/#parallel
      parallel {
        // start several test jobs in parallel, and they all
        // will use Cypress Dashboard to load balance any found spec files
        stage('tester A') {
          steps {
            echo "Running build ${env.BUILD_ID}"
            sh "hostname"
            sh "npm run e2e:smoke"
          }
        }

        // second tester runs the same command
        stage('tester B') {
          steps {
            echo "Running build ${env.BUILD_ID}"
            sh "hostname"
            sh "npm run e2e:smoketwo"
          }
        }
      }

    }

  }
}