pipeline {
  agent {
    docker {
      image 'cypress/browsers:node12.16.2-chrome81-ff75'
    }

  }
  stages {
    stage('build') {
      steps {
        echo "Running build ${env.BUILD_ID} on ${env.JENKINS_URL}"
        sh 'pwd && ls -l '
        sh 'npm ci'
        sh 'pwd && ls -l ./node_modules'
        sh 'npm run cy:verify'
      }
    }

  }
}