pipeline {
    agent {
        // this image provides everything needed to run Cypress
        docker {
        image 'cypress/base:10'
        // image 'cypress/included:4.8.0'
        }
    }

    stages {
        stage('Build') {
           steps{
               catchError {
                   // there a few default environment variables on Jenkins
                    // on local Jenkins machine (assuming port 8080) see
                    // http://localhost:8080/pipeline-syntax/globals#env
                    echo "Build........................................................."
                    sh 'hostname'
                    // sh 'npm install'
                    // sh 'npm run cy:verify'
               }
               echo currentBuild.result
            }
        }

        stage('1') {
            steps {
                script {
                    def tests = [:]
                    echo '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
                    def files = findFiles(glob: 'cypress/integration/examples/*.spec.js') 
                    // echo """${files[0].name} ${files[0].path} ${files[0].directory} ${files[0].length} ${files[0].lastModified}"""
                    for (f in files) {
                        tests["${f.path}"] = {
                            node {
                                stage("${f}") {
                                    echo """:::::::::::::::::   ${f.path} """
                                    sh 'npm cypress run --spec ${f}.path'
                                }
                            }
                        }
                    }
                    parallel tests
                }
            }
        }  

        // ==========================================================================================
        // stage('Run Tests In Parallel') {
        //     parallel {
        //         stage('First run'){
        //             steps{
        //                 catchError {
        //                     echo '::::::::::::::::::::::: First run ::::::::::::::::::::'
        //                     sh 'npm run e2e:smoke'
        //                 }
        //                 echo currentBuild.result
        //             }
        //         }
        //         stage('Second run'){
        //             steps{
        //                 catchError {
        //                     echo '::::::::::::::::::::::: Second run ::::::::::::::::::::'
        //                     sh 'npm run e2e:smoketwo'
        //                 }
        //                 echo currentBuild.result
        //             }
        //         }
        //     }
        // }
        // ==========================================================================================
        // stage('First run'){
        //     steps{
        //         catchError {
        //             echo '::::::::::::::::::::::: First run ::::::::::::::::::::'
        //             sh 'npm run e2e:smoke'
        //         }
        //         echo currentBuild.result
        //     }
        // }
        // stage('Second run'){
        //     steps{
        //         catchError {
        //             echo '::::::::::::::::::::::: Second run ::::::::::::::::::::'
        //             sh 'npm run e2e:smoketwo'
        //         }
        //         echo currentBuild.result
        //     }
        // }
    }
}