pipeline {
    agent {
        // this image provides everything needed to run Cypress
        docker {
        image 'cypress/base:10'
        // image 'cypress/included:4.8.0'
        }
    }
    parameters {
        choice(name: 'Browser', choices: ['Electron', 'Chrome', 'Firefox'], description: '')
        booleanParam(name: 'executeTests', defaultValue: true, description: '')
    }

    stages {
        stage('Build') {
           steps{
               catchError {
                   // there a few default environment variables on Jenkins
                    // on local Jenkins machine (assuming port 8080) see
                    // http://localhost:8080/pipeline-syntax/globals#env
                    echo "Build........................................................."
                    sh 'hostname'
                    sh 'npm install'
                    sh 'npm audit fix'
                    // sh 'npm run cy:verify'
               }
               echo currentBuild.result
            }
        }

        // ==========================================================================================
        stage('Run Tests In Parallel') {
            parallel {
                stage('First run'){
                    steps{
                        sh 'npm run e2e:smoke'
                    }
                }
                stage('Second run'){
                    steps{
                        sh 'npm run e2e:smoketwo'
                    }
                }
            }
        }

        stage('Dummy stage'){
            steps{
                echo 'Dummy stage'
            }
        }
        // ==========================================================================================
        // stage('First run'){
        //     steps{
        //         catchError {
        //             echo '::::::::::::::::::::::: First run ::::::::::::::::::::'
        //             sh 'npm run e2e:smoke'
        //         }
        //         echo currentBuild.result
        //     }
        // }
        // stage('Second run'){
        //     steps{
        //         catchError {
        //             echo '::::::::::::::::::::::: Second run ::::::::::::::::::::'
        //             sh 'npm run e2e:smoketwo'
        //         }
        //         echo currentBuild.result
        //     }
        // }
    }
}