pipeline {
    // agent {
    //     // this image provides everything needed to run Cypress
    //     docker {
    //     image 'cypress/base:10'
    //     // image 'cypress/included:4.8.0'
    //     }
    // }
    agent any
    parameters {
        choice(name: 'Browser', choices: ['Electron', 'Chrome', 'Firefox'], description: '')
        booleanParam(name: 'executeTests', defaultValue: true, description: '')
    }

    stages {
        stage('Build') {
            steps{
                echo "Build........................................................."
                script{
                    sh 'pwd'
                    sh 'ls -l'
                    sh 'ls -l /var/jenkins_home/workspace/parallel'
                    def testImage = docker.build("cy/base-image", "./ci-parallel")
                }
            }
        }

        // ==========================================================================================
        // stage('Run Tests In Parallel') {
        //     parallel {
        //         stage('First run'){
        //             steps{
        //                 sh 'npm run e2e:smoke'
        //             }
        //         }
        //         stage('Second run'){
        //             steps{
        //                 sh 'npm run e2e:smoketwo'
        //             }
        //         }
        //     }
        // }

        stage('Dummy stage'){
            steps{
                echo 'Dummy stage'
            }
        }
        // ==========================================================================================
        // stage('First run'){
        //     steps{
        //         catchError {
        //             echo '::::::::::::::::::::::: First run ::::::::::::::::::::'
        //             sh 'npm run e2e:smoke'
        //         }
        //         echo currentBuild.result
        //     }
        // }
        // stage('Second run'){
        //     steps{
        //         catchError {
        //             echo '::::::::::::::::::::::: Second run ::::::::::::::::::::'
        //             sh 'npm run e2e:smoketwo'
        //         }
        //         echo currentBuild.result
        //     }
        // }
    }
}